spring.application.name=studyhub

spring.datasource.url=jdbc:mysql://localhost:3306/studyhub?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Allow large base64 JSON payloads
server.tomcat.max-http-form-post-size=20MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Cloudinary Config
cloudinary.cloud_name=dzoub1nyq
cloudinary.api_key=557139242482563
cloudinary.api_secret=QfBhakVhkN3GUSl17gUqaCrqDuw